---
name: go-lint-test

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup golang
        id: golang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: .go-version

      - name: install golangci
        uses: giantswarm/install-binary-action@0797deb878056114fa54ee30c519f617716e8c69 # v3.1.1
        with:
          binary: "golangci-lint"
          version: "2.4.0"
          download_url: "https://github.com/golangci/golangci-lint/releases/download/v${version}/golangci-lint-${version}-linux-amd64.tar.gz"
          tarball_binary_path: "*/${binary}"
          smoke_test: "${binary} --version"

      - name: Run generate
        id: generate
        run: make generate

      - name: Run vet
        id: vet
        run: make vet

      - name: Run lint
        id: lint
        run: make lint

      - name: Run build
        id: build
        run: make build

      - name: Run test
        id: test
        run: make test
...
