---
name: release-notification

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  notify-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification on new release
        uses: cbrgm/telegram-github-action@d6efb871ef28c3596400d750aa2df16a36d8865d # v1.3.12
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            ðŸš€ New Release Published!
            Release Name: ${{ github.event.release.name }}
            Tag: ${{ github.event.release.tag_name }}
            Actor: ${{ github.actor }}
            Repository: ${{ github.repository }}
            Check it out: ${{ github.event.release.html_url }}

      - name: Send Mastodon Status on new release
        id: mastodon
        uses: cbrgm/mastodon-github-action@3ebdc72dcd894e1be460179eb0d01835f3689b2f # v2.1.23
        if: ${{ !github.event.repository.private }}
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          url: ${{ secrets.MASTODON_URL }}
          language: "en"
          message: |
            ðŸš€  ${{ github.repository }} ${{ github.event.release.name }} published!
            Check it out: ${{ github.event.release.html_url }}
...
