---
name: stale-issues-prs-branches
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        name: Setting issue as idle
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          stale-issue-message: "This issue is idle because it has been open for 90 days with no activity."
          stale-issue-label: idle
          days-before-stale: 90
          days-before-close: -1
          operations-per-run: 100
          exempt-issue-labels: backlog
      - uses: actions/stale@v9
        name: Setting PR as idle
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          stale-pr-message: "This PR is idle because it has been open for 90 days with no activity."
          stale-pr-label: idle
          days-before-stale: 90
          days-before-close: -1
          operations-per-run: 100
      - name: Cleanup Stale Branches
        uses: cbrgm/cleanup-stale-branches-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          dry-run: false
...
